inherits = "ashen"

"ui.virtual.jump-label" = { fg = "orange_golden", modifiers = [
  "bold"
]}

"ui.linenr" = { fg = "hint"}
"ui.linenr.selected" = { fg = "red"}

hint = { fg = "hint", bg = "g_10" }

[palette]
brown_dark = "#183831"
cursorline = "#232121"
hint = "#b2a6a6"
